# Generated by Django 5.0.4 on 2024-04-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75)),
                ("author", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "book_image",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Favorite"),
                ),
                ("listen_date", models.DateField(blank=True, null=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
