# Generated by Django 5.0.4 on 2024-05-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="book_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
