# Generated by Django 5.0.4 on 2024-05-03 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0007_alter_audiobook_book_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiobook",
            options={"ordering": ["-date_posted"]},
        ),
    ]
