# Generated by Django 5.0.4 on 2024-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0008_alter_audiobook_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="book_image",
            field=models.ImageField(
                blank=True, default="audio-book.png", null=True, upload_to="books/"
            ),
        ),
    ]
